- name: Install nginx service
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    remote_src: true


- name: Remove old app content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true