- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Remove old app content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes