- name: create application user
  ansible.builtin.user:
    name: {{"app_user"}}

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/${{component}}.zip
    dest: /app
    remote_src: yes

- name: Include task list in play
  ansible.builtin.import_tasks:
      file: app_pre_req.yml

- name: install nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app



